// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package contact

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Contact() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"page\" hx-swap-oob=\"true\" hx-target=\"page\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if ctx.Value("minimize") == "true" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"overflow-auto col-span-6\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"overflow-auto col-span-4\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("><div id=\"page-content\" hx-swap-oob=\"true\" hx-target=\"page-content\" role=\"tabpanel\" class=\"tab-content items-center justify-center m-11 col-span-4 bg-zinc-900 rounded-md\"><h1 class=\"m-2 context-align justify-center text-orange-600 uppercase text-bold text-4xl\">Contact Us </h1><div class=\"w-full m-10 text-orange-100\"><form class=\"m-10 text-2xl text-bold\"><h2 class=\"m-2\">Name of Company or Individual</h2><input type=\"text\" placeholder=\"Name\" class=\"h-10 px-3 py-2 text-sm  bg-black border rounded-md border-neutral-300 ring-offset-background placeholder:text-neutral-500 focus:border-neutral-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-neutral-400 disabled:cursor-not-allowed disabled:opacity-50\"><h2 class=\"m-2\">Email</h2><input type=\"text\" placeholder=\"Email\" class=\"h-10 px-3 py-2 text-sm bg-black border rounded-md border-neutral-300 ring-offset-background placeholder:text-neutral-500 focus:border-neutral-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-neutral-400 disabled:cursor-not-allowed disabled:opacity-50\"><h2 class=\"m-2\">Service Requested</h2><textarea class=\"h-10 px-3 py-2 text-sm  bg-black border rounded-md border-neutral-300 ring-offset-background placeholder:text-neutral-500 focus:border-neutral-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-neutral-400 disabled:cursor-not-allowed disabled:opacity-50\"></textarea> <button type=\"button\" class=\"m-5 items-center justify-center px-4 py-2 text-sm font-medium tracking-wide text-orange-800 transition-colors duration-100 bg-white border-1 border-orange-800 rounded-md hover:text-white hover:bg-orange-800\">Submit</button></form></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
