// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package blog

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Blog() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"page\" hx-swap-oob=\"true\" hx-target=\"page\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if ctx.Value("minimize") == "true" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"overflow-auto col-span-6\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"overflow-auto col-span-4\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("><div id=\"page-content\" hx-swap-oob=\"true\" role=\"tabpanel\" class=\"tab-content items-center justify-center text-white m-10 col-span-4\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ac ex a augue ornare eleifend at vel neque. Aenean aliquam urna et nisi convallis, id fringilla felis volutpat. Nullam maximus consequat tellus, venenatis malesuada magna tristique et. Nunc sed purus eu arcu vulputate dignissim. Suspendisse rhoncus pretium porta. Donec scelerisque, dui id sodales ultricies, leo ipsum interdum felis, ac tempor tortor ante non mauris. Duis ut auctor dolor. Fusce porta ante sed eleifend rutrum. Fusce cursus erat ac magna cursus semper. Nam id odio orci.</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
